# Generated by Django 4.2.4 on 2023-11-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
